GLOBAL_LIST_INIT(backpacklist, list(
	DBACKPACK,
	DDUFFELBAG,
	DSATCHEL,
	DMESSENGER,
	GBACKPACK,
	GDUFFELBAG,
	GSATCHEL,
	GMESSENGER,
	LSATCHEL,
))

GLOBAL_LIST_EMPTY(species_clothing_fallback_cache)
