export type AvailableJob = keyof typeof JOB2ICON;

/** Icon map of jobs to their fontawesome5 (free) counterpart. */
export const JOB2ICON = {
  AI: 'eye',
  Assistant: 'toolbox',
  'Atmospheric Technician': 'fan',
  Bartender: 'cocktail',
  'Bit Avatar': 'code',
  Bitrunner: 'gamepad',
  Botanist: 'seedling',
  'Bridge Assistant': 'building-shield',
  Captain: 'star',
  'Cargo Gorilla': 'paw',
  'Cargo Technician': 'box',
  'CentCom Commander': 'star',
  'CentCom Head Intern': 'pen-fancy',
  'CentCom Intern': 'pen-alt',
  'CentCom Official': 'medal',
  Chaplain: 'cross',
  Chef: 'utensils',
  Chemist: 'prescription-bottle',
  'Chief Engineer': 'helmet-safety',
  'Chief Medical Officer': 'staff-snake',
  Clown: 'face-grin-tears',
  Cook: 'utensils',
  Coroner: 'skull',
  Curator: 'book',
  'Cyber Police': 'qrcode',
  Cyborg: 'robot',
  Criminalist: 'user-secret',
  Geneticist: 'dna',
  'Head of Personnel': 'address-card',
  'Head of Security': 'person-military-pointing',
  'Big Brother': 'eye',
  Janitor: 'broom',
  'Internal Affairs Agent': 'feather-pointed',
  'Medical Doctor': 'briefcase-medical',
  Mime: 'comment-slash',
  Paramedic: 'truck-medical',
  'Personal AI': 'mobile-alt',
  Prisoner: 'handcuffs',
  Psychologist: 'brain',
  Quartermaster: 'clipboard-check',
  'Research Director': 'graduation-cap',
  Roboticist: 'gear',
  Scientist: 'flask',
  'Security Officer (Cargo)': 'person-rifle',
  'Security Officer (Engineering)': 'person-rifle',
  'Security Officer (Medical)': 'person-rifle',
  'Security Officer (Science)': 'person-rifle',
  'Security Officer': 'person-rifle',
  'Shaft Miner': 'digging',
  Steward: 'user-tie',
  'Deck Engineer': 'screwdriver-wrench',
  'Syndicate Operative': 'dragon',
  'Veteran Security Advisor': 'ribbon',
  'Pun Pun': 'paw',
  Warden: 'person-military-rifle',
} as const;
